default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: saas-project-app_development
test:
  <<: *default
  database: saas-project-app_test

production:
  <<: *default
  database: saas-project-app_production
  username: saas-project-app
  password: <%= ENV['SAAS-PROJECT-APP_DATABASE_PASSWORD'] %>
